spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/db
    name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
     ddl-auto: update
#  data:
#    redis:
#      host: localhost
#      port: 6379
  security:
    oauth2:
      client:
        registration:
          github:
            scope:
              - user:email
            authorization-uri: https://github.com/login/oauth/authorize
            client-id: 765fc23c20c71dc7ec13
            client-secret: 353490633a7c3368e3efb9fb25514b37e89524fb
#  cache:
#    type: redis
#    redis:
#      time-to-live: 300000

app:
  namespace: http://schemas.xmlsoap.org/soap/envelope/
  dev-url: http://localhost:8080
  prod-url: http://localhost:8080
