
#spring:
#  batch:
#    job:
#      enabled: false
#    initialize-schema: always
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: sa
#    password: QuillRocks!
#    url: jdbc:sqlserver://localhost:11433;databaseName=ast;encrypt=true;trustServerCertificate=true;
#  jpa:
#    database-platform: org.hibernate.dialect.SQLServerDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  batch:
#    job:
#      enabled: false
#    initialize-schema: always
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: password
#    url: jdbc:mysql://localhost:3306/db
#    name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#     ddl-auto: update
spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password
    url: jdbc:postgresql://localhost:5432/ksas
    name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto: update
#  data:
#    redis:
#      host: localhost
#      port: 6379
  security:
    oauth2:
      client:
        registration:
          github:
            scope:
              - user:email
            authorization-uri: https://github.com/login/oauth/authorize
            client-id: 765fc23c20c71dc7ec13
            client-secret: 353490633a7c3368e3efb9fb25514b37e89524fb
#  cache:
#    type: redis
#    redis:
#      time-to-live: 300000

xmlRootNamespace: http://schemas.xmlsoap.org/soap/envelope/
app:
  spel: test
  namespace: http://schemas.xmlsoap.org/soap/envelope/
  dev-url: http://localhost:8080
  prod-url: http://localhost:8080
tar:
  migration-location: "db/migrations/postgrest"
  database-type: OTHER
  migration-enable: false
  migration-show: false
  start-with-version: 1
  stop-with-version: 12
#  ignore-version: [1,3,11]